const CONFIG = {
  // 博客標題 雙語言
  TYPOGRAPHY_BLOG_NAME: process.env.NEXT_PUBLIC_TYPOGRAPHY_BLOG_NAME || '活字印刷',
  TYPOGRAPHY_BLOG_NAME_EN: process.env.NEXT_PUBLIC_TYPOGRAPHY_BLOG_NAME_EN || process.env.NEXT_PUBLIC_TYPOGRAPHY_BLOG_NAME || 'Typography',

  TYPOGRAPHY_POST_AD_ENABLE: process.env.NEXT_PUBLIC_TYPOGRAPHY_POST_AD_ENABLE || false, // 文章列表是否插入广告

  TYPOGRAPHY_POST_COVER_ENABLE: process.env.NEXT_PUBLIC_TYPOGRAPHY_POST_COVER_ENABLE || false, // 是否展示博客封面

  TYPOGRAPHY_ARTICLE_RECOMMEND_POSTS: process.env.NEXT_PUBLIC_TYPOGRAPHY_ARTICLE_RECOMMEND_POSTS || true, // 文章详情底部显示推荐

  // 菜单配置
  TYPOGRAPHY_MENU_CATEGORY: true, // 显示分类
  TYPOGRAPHY_MENU_TAG: true, // 显示标签
  TYPOGRAPHY_MENU_ARCHIVE: true, // 显示归档

  // 目录配置
  TYPOGRAPHY_TOC_ENABLE: process.env.NEXT_PUBLIC_TYPOGRAPHY_TOC_ENABLE !== 'false', // 是否显示目录，默认开启
  TYPOGRAPHY_TOC_MAX_DEPTH: parseInt(process.env.NEXT_PUBLIC_TYPOGRAPHY_TOC_MAX_DEPTH) || 3, // 目录最大层级，支持1-6级
  TYPOGRAPHY_TOC_COLLAPSE_ON_SCROLL: process.env.NEXT_PUBLIC_TYPOGRAPHY_TOC_COLLAPSE_ON_SCROLL !== 'false', // 滚动时折叠非当前位置的子目录，默认关闭
  TYPOGRAPHY_TOC_SCROLL_BEHAVIOR: process.env.NEXT_PUBLIC_TYPOGRAPHY_TOC_SCROLL_BEHAVIOR || 'instant', // 滚动行为：'smooth' 或 'instant'
}
export default CONFIG
